import { Router } from "express";
import { CreateUserController } from "./controller/users/CreateUserController";
import { ListUserController } from "./controller/users/ListUserController";
import { DeleteUserController } from "./controller/users/DeleteUserConstroller";
import { EditUserController } from "./controller/users/EditUserController";
import { CreateProdutoController } from "./controller/produto/CreateProdutoController";
import { ListProdutoController } from "./controller/produto/ListProdutoController";
import { DeleteProdutoController } from "./controller/produto/DeleteProdutoController";
import { EditProdutoController } from "./controller/produto/EditProdutoController";
import { CreateCarroController } from "./controller/carro/CreateCarroController";
import { DeleteCarroController } from "./controller/carro/DeleteCarroController";
import { EditCarroController } from "./controller/carro/EditCarroController";
import { ListCarroController } from "./controller/carro/ListCarroController";
import { CreateFilmeController } from "./controller/filme/CreateFilmeController";
import { ListFilmeController } from "./controller/filme/ListFilmeController";
import { EditFilmeController } from "./controller/filme/EditFilmeController";
import { DeleteFilmeController } from "./controller/filme/DeleteFilmeController";
import { AutenticateUserController } from "./controller/autentication/AutenticateUserController";
import { EnsureAutenticated } from "./middleware/EnsureAutenticated";
import { CreateCartaoController } from "./controller/cartaocredito/CreateCartaoControler";
import { ListCartaoController } from "./controller/cartaocredito/ListCartaoController";
import { EditCartaoController } from "./controller/cartaocredito/EditCartaoController";
import { DeleteCartaoController } from "./controller/cartaocredito/DeleteCartaoController";
import { CreateVideogameController } from "./controller/videogame/CreateVideogameController";
import { ListVideogameController } from "./controller/videogame/ListVideogameController";
import { EditVideogameController } from "./controller/videogame/EditVideogameController";
import { DeleteVideogameController } from "./controller/videogame/DeleteVideogameService";
import { CreateReservaController } from "./controller/reserva/CreateReservaController";
import { ListReservaController } from "./controller/reserva/ListReservaController";
import { EditReservaController } from "./controller/reserva/EditReservaController";
import { DeleteReservaController } from "./controller/reserva/DeleteReservaService";
import { CreatePerfilController } from "./controller/perfil/createperfilcontroller";
import { ListPerfilController } from "./controller/perfil/ListPerfilController";
import { CreateCategoriaController } from "./controller/categoria/CreateCategoriaController";
import { ListCategoriaController } from "./controller/categoria/ListCategoriaController";
import { CreateVendaController } from "./controller/vendas/CreateVendaController";
import { ListVendaController } from "./controller/vendas/ListVendaController";
import { EditCategoriaController } from "./controller/categoria/EditCategoriaController";
import { DeleteCategoriController } from "./controller/categoria/DeleteCategoriaController";
import { ListOneCategoriaController } from "./controller/categoria/ListOneCategoriaController";
import { ListOneProdutoController } from "./controller/produto/ListOneProdutoController";
import { UpdateVendaController } from "./controller/vendas/UpdateVendaController";
import { DeleteVendaController } from "./controller/vendas/DeleteVendaController";
import { ListOneVendaController } from "./controller/vendas/ListOneVendaController";
import { ListOneUserController } from "./controller/users/ListOneUserController";


const createusercontroller = new CreateUserController();
const listusercontroller = new ListUserController();
const deleteusercontroller = new DeleteUserController();
const editusercontroller = new EditUserController();
const createprodutocontroller = new CreateProdutoController();
const listprodutocontroller = new ListProdutoController();
const deleteprodutocontroller = new DeleteProdutoController();
const editprodutocontroller = new EditProdutoController();
const createcarrocontroller = new CreateCarroController();
const deletecarrocontroller = new DeleteCarroController();
const editcarrocontroller = new EditCarroController();
const listcarrocontroller = new ListCarroController();
const autenticateusercontroller = new AutenticateUserController();
const createfilmecontroller = new CreateFilmeController();
const listfilmecontroller = new ListFilmeController();
const editfilmecontroller = new EditFilmeController();
const deletefilmecontroller = new DeleteFilmeController();
const createcartaocontroller = new CreateCartaoController();
const listcartaocontroller = new ListCartaoController();
const editcartaocontroller = new EditCartaoController();
const deletecartaocontroller = new DeleteCartaoController();
const createvideogamecontroller = new CreateVideogameController();
const listvideogamecontroller = new ListVideogameController();
const editvideogamecontroller = new EditVideogameController();
const deletevideogamecontroller = new DeleteVideogameController();
const createreservacontroller = new CreateReservaController();
const listreservacontroller = new ListReservaController();
const editreservacontroller = new EditReservaController();
const deletereservacontroller = new DeleteReservaController();
const createperfilcontroller = new CreatePerfilController();
const listperfilcontroller = new ListPerfilController();
const createcategoriacontroller = new CreateCategoriaController();
const listcategoriacontroller = new ListCategoriaController();
const createvendacontroller = new CreateVendaController();
const listvendacontroller = new ListVendaController();
const editcategoriacontroller = new EditCategoriaController();
const deletecategoriacontroller = new DeleteCategoriController();
const listonecategoriacontroller = new ListOneCategoriaController();
const listoneprodutocontroller = new ListOneProdutoController();
const updatevendacontroller = new UpdateVendaController();
const deletevendacontroller = new DeleteVendaController();
const listonevendacontroller = new ListOneVendaController();
const listoneusercontroller = new ListOneUserController();
const router = Router();

router.post("/login",autenticateusercontroller.handle);
router.post("/reset",autenticateusercontroller.resetpassword);


router.post("/users", createusercontroller.handle);
router.get("/users", listusercontroller.handle);
router.delete("/users/:id", deleteusercontroller.handle);
router.put("/users", editusercontroller.handle);
router.post("/produtos", createprodutocontroller.handle);
router.get("/produtos", listprodutocontroller.handle);
router.delete("/produtos/:id", deleteprodutocontroller.handle);
router.put("/produtos", editprodutocontroller.handle);
router.post("/carro", createcarrocontroller.handle);
router.delete("/carro/:id", deletecarrocontroller.handle);
router.put("/carro", editcarrocontroller.handle);
router.get("/carro", listcarrocontroller.handle);
router.post("/filme", createfilmecontroller.handle);
router.get("/filme", listfilmecontroller.handle);
router.put("/filme", editfilmecontroller.handle)
router.delete("/filme/:id", deletefilmecontroller.handle);
router.post("/cartao", createcartaocontroller.handle);
router.get("/cartao", listcartaocontroller.handle);
router.put("/cartao", editcartaocontroller.handle);
router.delete("/cartao/:id", deletecartaocontroller.handle);
router.post("/videogame", createvideogamecontroller.handle);
router.get("/videogame", listvideogamecontroller.handle);
router.put("/videogame", editvideogamecontroller.handle);
router.delete("/videogame/:id", deletevideogamecontroller.handle);
router.post("/reserva", createreservacontroller.handle);
router.get("/reserva", listreservacontroller.handle);
router.put("/reserva", editreservacontroller.handle);
router.delete("/reserva/:id", deletereservacontroller.handle);
router.post("/perfil", createperfilcontroller.handle);
router.get("/perfil", listperfilcontroller.handle);
router.post("/categoria", createcategoriacontroller.handle);
router.get("/categoria", listcategoriacontroller.handle);
router.post("/venda", createvendacontroller.handle);
router.get("/venda", listvendacontroller.handle);
router.put("/categoria", editcategoriacontroller.handle);
router.delete("/categoria/:id", deletecategoriacontroller.handle);
router.get("/categoria2/:id", listonecategoriacontroller.handle);
router.get("/produtos2/:id", listoneprodutocontroller.handle);
router.put("/venda", updatevendacontroller.handle);
router.delete("/venda/:id", deletevendacontroller.handle);
router.get("/venda2/:id", listonevendacontroller.handle);
router.get("/user2/:id", listoneusercontroller.handle);
router.use(EnsureAutenticated);

export {router}